spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:db2://192.168.56.12:50000/mbidb
    username: mbi
    password: mbi
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

server:
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 500
    basedir: E:/mbi
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
